#include "consts.h"

const ValueName LogPacketTypeID_To_Name[] = {
    {CDMA_Paging_Channel_Message,
        "CDMA_Paging_Channel_Message",false},

    {_1xEV_Connection_Attempt,
        "1xEV_Connection_Attempt", true},
    {_1xEV_Connection_Release,
        "1xEV_Connection_Release", true},
    {_1xEV_Signaling_Control_Channel_Broadcast,
        "1xEV_Signaling_Control_Channel_Broadcast",false},
    {_1xEV_Connected_State_Search_Info,
        "1xEV_Connected_State_Search_Info", true},
    {Srch_TNG_1x_Searcher_Dump,
        "Srch_TNG_1x_Searcher_Dump", false},
    {_1xEV_Rx_Partial_MultiRLP_Packet,
        "1xEV_Rx_Partial_MultiRLP_Packet", true},
    {_1xEVDO_Multi_Carrier_Pilot_Sets,
        "1xEVDO_Multi_Carrier_Pilot_Sets", false},
    {HDR_Pilot_Sets,
        "HDR_Pilot_Sets", false},

    {WCDMA_Search_Cell_Reselection_Rank,
        "WCDMA_Search_Cell_Reselection_Rank", false},
    {WCDMA_RRC_States,
        "WCDMA_RRC_States", false},
    {WCDMA_CELL_ID,
        "WCDMA_RRC_Serv_Cell_Info",true},
    {WCDMA_Signaling_Messages,
        "WCDMA_RRC_OTA_Packet",true},

    {UMTS_NAS_GMM_State,
        "UMTS_NAS_GMM_State",true},
    {UMTS_NAS_MM_State,
        "UMTS_NAS_MM_State",true},
    {UMTS_NAS_MM_REG_State,
        "UMTS_NAS_MM_REG_State",true},
    {UMTS_NAS_OTA,
        "UMTS_NAS_OTA_Packet",true},

    {LTE_RRC_OTA_Packet,
        "LTE_RRC_OTA_Packet",true},
    {LTE_RRC_MIB_Message_Log_Packet,
        "LTE_RRC_MIB_Packet",true},
    {LTE_RRC_MIB_Message_Log_Packet,
        "LTE_RRC_MIB_Message_Log_Packet",true},
    {LTE_RRC_Serv_Cell_Info_Log_Packet,
        "LTE_RRC_Serv_Cell_Info",true},

    {LTE_NAS_ESM_Plain_OTA_Incoming_Message,
        "LTE_NAS_ESM_OTA_Incoming_Packet",true},
    {LTE_NAS_ESM_Plain_OTA_Outgoing_Message,
        "LTE_NAS_ESM_OTA_Outgoing_Packet",true},
    {LTE_NAS_EMM_Plain_OTA_Incoming_Message,
        "LTE_NAS_EMM_OTA_Incoming_Packet",true},
    {LTE_NAS_EMM_Plain_OTA_Outgoing_Message,
        "LTE_NAS_EMM_OTA_Outgoing_Packet",true},
    {LTE_NAS_EMM_State,
        "LTE_NAS_EMM_State",true},
    {LTE_NAS_ESM_State,
        "LTE_NAS_ESM_State",true},

    {LTE_PDCP_DL_Config,
        "LTE_PDCP_DL_Config", true},
    {LTE_PDCP_UL_Config,
        "LTE_PDCP_UL_Config", true},
    {LTE_PDCP_UL_Data_PDU,
        "LTE_PDCP_UL_Data_PDU", true},
    {LTE_PDCP_DL_Ctrl_PDU,
        "LTE_PDCP_DL_Ctrl_PDU", true},
    {LTE_PDCP_UL_Ctrl_PDU,
        "LTE_PDCP_UL_Ctrl_PDU", true},
    {LTE_PDCP_DL_Cipher_Data_PDU,
        "LTE_PDCP_DL_Cipher_Data_PDU", false},
    {LTE_PDCP_UL_Cipher_Data_PDU,
        "LTE_PDCP_UL_Cipher_Data_PDU", false},
    {LTE_PDCP_DL_Stats,
        "LTE_PDCP_DL_Stats", true},
    {LTE_PDCP_UL_Stats,
        "LTE_PDCP_UL_Stats", true},
    {LTE_PDCP_DL_SRB_Integrity_Data_PDU,
        "LTE_PDCP_DL_SRB_Integrity_Data_PDU", true},
    {LTE_PDCP_UL_SRB_Integrity_Data_PDU,
        "LTE_PDCP_UL_SRB_Integrity_Data_PDU", true},

    {LTE_MAC_Configuration,
        "LTE_MAC_Configuration", false},
    {LTE_MAC_Rach_Trigger,
        "LTE_MAC_Rach_Trigger", false},
    {LTE_MAC_Rach_Attempt,
        "LTE_MAC_Rach_Attempt", false},
    {LTE_MAC_UL_Transport_Block,
        "LTE_MAC_UL_Transport_Block", true},
    {LTE_MAC_DL_Transport_Block,
        "LTE_MAC_DL_Transport_Block", true},
    {LTE_MAC_UL_Buffer_Status_Internal,
        "LTE_MAC_UL_Buffer_Status_Internal", false},
    {LTE_MAC_UL_Tx_Statistics,
        "LTE_MAC_UL_Tx_Statistics", false},

    {LTE_RLC_UL_Config_Log_Packet,
        "LTE_RLC_UL_Config_Log_Packet", true},
    {LTE_RLC_DL_Config_Log_Packet,
        "LTE_RLC_DL_Config_Log_Packet", true},
    {LTE_RLC_UL_AM_All_PDU,
        "LTE_RLC_UL_AM_All_PDU", true},
    {LTE_RLC_DL_AM_All_PDU,
        "LTE_RLC_DL_AM_All_PDU", true},
    {LTE_RLC_UL_Stats,
        "LTE_RLC_UL_Stats", true},
    {LTE_RLC_DL_Stats,
        "LTE_RLC_DL_Stats", true},

    {LTE_PUCCH_Power_Control,
        "LTE_PHY_PUCCH_Power_Control", false},
    {LTE_PUSCH_Power_Control,
        "LTE_PHY_PUSCH_Power_Control", false},
    {LTE_PDCCH_PHICH_Indication_Report,
        "LTE_PHY_PDCCH_PHICH_Indication_Report", false},
    {LTE_PDSCH_Stat_Indication,
        "LTE_PHY_PDSCH_Stat_Indication", false},

    {LTE_PHY_Connected_Mode_LTE_Intra_Freq_Meas_Results,
        "LTE_PHY_Connected_Mode_Intra_Freq_Meas",true},
    {LTE_PHY_CDMA_MEAS,
        "LTE_PHY_Inter_RAT_CDMA_Measurement", true},
    {LTE_PHY_IRAT_Measurement_Request,
        "LTE_PHY_Inter_RAT_Measurement",true},
    {LTE_PHY_IRAT_MDB,
        "LTE_PHY_Inter_RAT_Measurement", true},
    {LTE_PHY_RLM_Report,
        "LTE_PHY_RLM_Report", false},
    {LTE_PHY_System_Scan_Results,
        "LTE_PHY_System_Scan_Results", false},
    {LTE_PHY_Idle_Neighbor_Cell_Meas,
        "LTE_PHY_Idle_Neighbor_Cell_Meas", false},
    {LTE_PHY_Serving_Cell_Measurement_Result,
        "LTE_PHY_Serv_Cell_Measurement",true},
    {LTE_PHY_Connected_Mode_Neighbor_Meas_Req_Resp,
        "LTE_PHY_Connected_Mode_Neighbor_Measurement",true},
    {LTE_PHY_CDRX_Events_Info,
        "LTE_RRC_CDRX_Events_Info", false},
    {LTE_PHY_Inter_Freq_Log,
        "LTE_PHY_Inter_Freq_Log", true},
    {LTE_PHY_BPLMN_Cell_Request,
        "LTE_PHY_BPLMN_Cell_Request", false},
    {LTE_PHY_BPLMN_Cell_Confirm,
        "LTE_PHY_BPLMN_Cell_Confirm", false},

    {LTE_PHY_Serving_Cell_COM_Loop,
        "LTE_PHY_Serving_Cell_COM_Loop", false},
    {LTE_PHY_PDSCH_Demapper_Configuration,
        "LTE_PHY_PDSCH_Packet",true},
    {LTE_PHY_PDCCH_Decoding_Result,
        "LTE_PHY_PDCCH_Decoding_Result", false},
    {LTE_PHY_PDSCH_Decoding_Result,
        "LTE_PHY_PDSCH_Decoding_Result", false},
    {LTE_PHY_PUSCH_Tx_Report,
        "LTE_PHY_PUSCH_Tx_Report", false},
    {LTE_PHY_PUCCH_Tx_Report,
        "LTE_PHY_PUCCH_Tx_Report", false},
    {LTE_PHY_PUCCH_CSF,
        "LTE_PHY_PUCCH_CSF", false},
    {LTE_PHY_PUSCH_CSF,
        "LTE_PHY_PUSCH_CSF", false},

    {GSM_Surround_Cell_BA_List,
        "GSM_Surround_Cell_BA_List", false},
    {GSM_RR_Cell_Reselection_Parameters,
        "GSM_RR_Cell_Reselection_Parameters", false},
    {GSM_RR_Cell_Information,
        "GSM_RR_Cell_Information", false},
    {GSM_RR_Cell_Reselection_Meas,
        "GSM_RR_Cell_Reselection_Meas", false},
    {GSM_RR_Signaling_Message,
        "GSM_RR_Signaling_Message", false},

    {GSM_DSDS_RR_Cell_Reselection_Parameters,
        "GSM_DSDS_RR_Cell_Reselection_Parameters", false},
    {GSM_DSDS_RR_Cell_Information,
        "GSM_DSDS_RR_Cell_Information", false},
    {GSM_DSDS_RR_Signaling_Message,
        "GSM_DSDS_RR_Signaling_Message", false},

    {LTE_NB1_ML1_GM_DCI_Info,
        "LTE_NB1_ML1_GM_DCI_Info", true},
    {LTE_NB1_ML1_GM_TX_Report,
        "LTE_NB1_ML1_GM_TX_Report", true},
    {LTE_NB1_ML1_GM_PDSCH_STAT_Ind,
        "LTE_NB1_ML1_GM_PDSCH_STAT_Ind", true},
    {LTE_NB1_ML1_CDRX_Events_Info,
        "LTE_NB1_ML1_CDRX_Events_Info", true},
    {LTE_NB1_ML1_Sum_Sys_Info,
        "LTE_NB1_ML1_Sum_Sys_Info", true},
    {LTE_NB1_ML1_Cell_Resel,
        "LTE_NB1_ML1_Cell_Resel", true},
    {LTE_NB1_NBR_Cell_Meas,
        "LTE_NB1_NBR_Cell_Meas", true},
    {LTE_NB1_ML1_Search_PBCH_Decode,
        "LTE_NB1_ML1_Search_PBCH_Decode", true},
    {LTE_NB1_ML1_DLM_Decode_Page,
        "LTE_NB1_ML1_DLM_Decode_Page", true},

    {NR_NAS_SM5G_Plain_OTA_Incoming_Msg,
        "5G_NR_NAS_SM_Plain_OTA_Incoming_Msg", true},
    {NR_NAS_SM5G_Plain_OTA_Outgoing_Msg,
        "5G_NR_NAS_SM_Plain_OTA_Outgoing_Msg", true},

    {NR_NAS_MM5G_Plain_OTA_Incoming_Msg,
        "5G_NR_NAS_MM_Plain_OTA_Incoming_Msg", true},
    {NR_NAS_MM5G_Plain_OTA_Outgoing_Msg,
        "5G_NR_NAS_MM_Plain_OTA_Outgoing_Msg", true},
    {NR_NAS_MM5G_Plain_OTA_Container_Msg,
        "5G_NR_NAS_MM5G_Plain_OTA_Container_Msg", true},
    {NR_NAS_MM5G_State,
        "5G_NR_NAS_MM5G_State",true},

    {NR_RRC_OTA_Packet,
        "5G_NR_RRC_OTA_Packet", true},

    {NR_PDCP_UL_Control_Pdu,
        "5G_NR_PDCP_UL_Control_Pdu", true},

    {NR_L2_UL_TB,
        "5G_NR_L2_UL_TB", true},
    {NR_L2_UL_BSR,
        "5G_NR_L2_UL_BSR", true},

    {NR_RLC_DL_Stats,
        "5G_NR_RLC_DL_Stats", true},

    {NR_MAC_UL_TB_Stats,
        "5G_NR_MAC_UL_TB_Stats", true},
    {NR_MAC_UL_Physical_Channel_Schedule_Report,
        "5G_NR_MAC_UL_Physical_Channel_Schedule_Report", true},
    {NR_MAC_PDSCH_Stats,
        "5G_NR_MAC_PDSCH_Stats", true},
    {NR_MAC_RACH_Trigger,
        "5G_NR_MAC_RACH_Trigger",true},

    {NR_LL1_FW_Serving_FTL,
        "5G_NR_LL1_FW_Serving_FTL", true},
    {NR_ML1_Searcher_Measurement_Database_Update_Ext,
        "5G_NR_ML1_Searcher_Measurement_Database_Update_Ext", true},
    {NR_ML1_Serving_Cell_Beam_Management,
        "5G_NR_ML1_Serving_Cell_Beam_Management", true},

    {Modem_debug_message,
        "Modem_debug_message", false},
    {GNSS_GPS_Measurement_Report,
        "GNSS_GPS_Measurement_Report", true},
    {GNSS_Glonass_Measurement_Report,
        "GNSS_Glonass_Measurement_Report", true},
    {GNSS_BDS_Measurement_Report,
        "GNSS_BDS_Measurement_Report", true},
    {GNSS_GAL_Measurement_Report,
        "GNSS_GAL_Measurement_Report", true},
};

// Computed once here; all other TUs use LogPacketTypeID_To_Name_n.
// sizeof on an incomplete extern array would be a compile error, so
// the count must live in the same TU as the definition.
const int LogPacketTypeID_To_Name_n =
    sizeof(LogPacketTypeID_To_Name) / sizeof(ValueName);

bool
is_log_packet(const char *b, size_t length) {
    return length >= 2 && b[0] == '\x10';
}

bool
is_debug_packet(const char *b, size_t length) {
    return length >= 2 && (b[0] == '\x79' || b[0] == '\x92');
    // return length >=2 && (b[0] == '\x92');  //Yuanjie: optimization for iCellular, avoid unuseful debug msg
    // return length >=2 && (b[0] ==  '\x79');
}

bool
is_custom_packet (const char *b, size_t length) {
    return length >= 2 && b[0] == '\xee' && b[1] == '\xee';
}